export type DemoProductSeed = {
  name: string;
  sku: string;
  brand: string;
  shortDescription: string;
  description: string;
  categorySlug: string;
  price: number;
  unit: string;
  stock: number;
  lowStockThreshold: number;
  leadTimeText: string;
  isFeatured: boolean;
  imageAlt: string;
  imageKey: string;
  daysOffset: number;
  tiers: Array<{ minQuantity: number; price: number }>;
};

export const demoProductSeeds: DemoProductSeed[] = [
  {
    name: "Disco de corte industrial 4.5 pulg",
    sku: "ABR-001",
    brand: "Acavike Select",
    shortDescription: "Disco para acero con alto rendimiento en taller y mantenimiento.",
    description: "Disco de corte multipropósito para operaciones industriales de uso continuo.",
    categorySlug: "abrasivos",
    price: 48.5,
    unit: "pieza",
    stock: 120,
    lowStockThreshold: 20,
    leadTimeText: "Entrega inmediata",
    isFeatured: true,
    imageAlt: "Disco de corte industrial",
    imageKey: "abrasive-disc",
    daysOffset: 44,
    tiers: [
      { minQuantity: 10, price: 45.9 },
      { minQuantity: 50, price: 43.25 },
    ],
  },
  {
    name: "Caja corrugada doble pared 60 x 40",
    sku: "EMP-002",
    brand: "Acavike Supply",
    shortDescription: "Empaque resistente para logística interna y embarque.",
    description: "Caja corrugada doble pared con buena resistencia para cargas medianas.",
    categorySlug: "empaque",
    price: 39.9,
    unit: "pieza",
    stock: 240,
    lowStockThreshold: 40,
    leadTimeText: "24 a 48 horas",
    isFeatured: true,
    imageAlt: "Caja corrugada",
    imageKey: "box",
    daysOffset: 43,
    tiers: [
      { minQuantity: 25, price: 36.4 },
      { minQuantity: 100, price: 33.8 },
    ],
  },
  {
    name: "Guante anticorte recubierto",
    sku: "SEG-003",
    brand: "Acavike Guard",
    shortDescription: "Guante para operación industrial con buen agarre.",
    description: "Guante anticorte nivel intermedio para almacén, manufactura y empaque.",
    categorySlug: "equipo-de-seguridad",
    price: 89,
    unit: "par",
    stock: 75,
    lowStockThreshold: 15,
    leadTimeText: "Entrega inmediata",
    isFeatured: true,
    imageAlt: "Guante anticorte",
    imageKey: "glove",
    daysOffset: 42,
    tiers: [
      { minQuantity: 12, price: 83.5 },
      { minQuantity: 48, price: 79.9 },
    ],
  },
  {
    name: "Desengrasante industrial concentrado",
    sku: "LMP-004",
    brand: "Acavike Clean",
    shortDescription: "Limpieza profunda para taller, piso y maquinaria ligera.",
    description: "Solución concentrada de limpieza industrial para mantenimiento y sanitización.",
    categorySlug: "limpieza",
    price: 315,
    unit: "garrafa",
    stock: 32,
    lowStockThreshold: 10,
    leadTimeText: "48 horas",
    isFeatured: true,
    imageAlt: "Desengrasante industrial",
    imageKey: "degreaser",
    daysOffset: 41,
    tiers: [
      { minQuantity: 4, price: 299 },
      { minQuantity: 12, price: 287.5 },
    ],
  },
  {
    name: "Perfil estructural ligero 3 m",
    sku: "FAB-006",
    brand: "Acavike Metal",
    shortDescription: "Perfil para fabricación ligera y adecuaciones de planta.",
    description: "Perfil estructural comercial para soporte, racks y fabricación menor.",
    categorySlug: "fabricacion",
    price: 185,
    unit: "barra",
    stock: 26,
    lowStockThreshold: 8,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Perfil estructural",
    imageKey: "steel-profile",
    daysOffset: 40,
    tiers: [
      { minQuantity: 10, price: 176 },
      { minQuantity: 30, price: 169.5 },
    ],
  },
  {
    name: "Taladro percutor 1/2",
    sku: "HER-009",
    brand: "Acavike Tools",
    shortDescription: "Herramienta portátil para mantenimiento general.",
    description: "Taladro percutor de uso industrial ligero con mandril metálico.",
    categorySlug: "herramienta",
    price: 1890,
    unit: "pieza",
    stock: 9,
    lowStockThreshold: 4,
    leadTimeText: "48 horas",
    isFeatured: true,
    imageAlt: "Taladro percutor",
    imageKey: "drill",
    daysOffset: 39,
    tiers: [{ minQuantity: 5, price: 1785 }],
  },
  {
    name: "Tornillo hexagonal galvanizado",
    sku: "TOR-010",
    brand: "Acavike Fix",
    shortDescription: "Fijación estándar para mantenimiento e instalación.",
    description: "Tornillo galvanizado de uso general con cabeza hexagonal.",
    categorySlug: "tornilleria",
    price: 3.8,
    unit: "pieza",
    stock: 900,
    lowStockThreshold: 120,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Tornillo galvanizado",
    imageKey: "screw",
    daysOffset: 38,
    tiers: [
      { minQuantity: 100, price: 3.4 },
      { minQuantity: 500, price: 3.1 },
    ],
  },
  {
    name: "Renta de escalera dieléctrica 10 peldaños",
    sku: "REN-011",
    brand: "Acavike Rental",
    shortDescription: "Renta diaria para trabajos de mantenimiento y seguridad.",
    description: "Servicio de renta con disponibilidad sujeta a programación operativa.",
    categorySlug: "renta",
    price: 650,
    unit: "día",
    stock: 4,
    lowStockThreshold: 1,
    leadTimeText: "Bajo programación",
    isFeatured: false,
    imageAlt: "Escalera dieléctrica",
    imageKey: "ladder",
    daysOffset: 37,
    tiers: [{ minQuantity: 5, price: 590 }],
  },
  {
    name: "Cinta de señalización amarilla",
    sku: "CON-008",
    brand: "Acavike Build",
    shortDescription: "Cinta para delimitación temporal de zonas de trabajo.",
    description: "Cinta de señalización visible para obra, mantenimiento y seguridad perimetral.",
    categorySlug: "construccion",
    price: 62,
    unit: "rollo",
    stock: 190,
    lowStockThreshold: 25,
    leadTimeText: "Entrega inmediata",
    isFeatured: true,
    imageAlt: "Cinta de señalización",
    imageKey: "warning-tape",
    daysOffset: 36,
    tiers: [
      { minQuantity: 24, price: 58.5 },
      { minQuantity: 96, price: 54.1 },
    ],
  },
  {
    name: "Silla operativa tapizada",
    sku: "OFF-007",
    brand: "Acavike Office",
    shortDescription: "Mobiliario funcional para áreas administrativas.",
    description: "Silla operativa con altura ajustable y respaldo de soporte medio.",
    categorySlug: "oficina",
    price: 1399,
    unit: "pieza",
    stock: 14,
    lowStockThreshold: 4,
    leadTimeText: "3 a 5 días hábiles",
    isFeatured: true,
    imageAlt: "Silla operativa",
    imageKey: "office-chair",
    daysOffset: 35,
    tiers: [{ minQuantity: 10, price: 1299 }],
  },
  {
    name: "Kit de café y azúcar para oficina",
    sku: "COM-005",
    brand: "Acavike Pantry",
    shortDescription: "Abasto básico para estaciones de servicio internas.",
    description: "Kit genérico para consumo interno con café soluble, azúcar y vasos.",
    categorySlug: "comestibles",
    price: 420,
    unit: "kit",
    stock: 18,
    lowStockThreshold: 6,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Kit de café",
    imageKey: "coffee-kit",
    daysOffset: 34,
    tiers: [{ minQuantity: 6, price: 399 }],
  },
  {
    name: "Lija de agua grano 400",
    sku: "ABR-012",
    brand: "Acavike Select",
    shortDescription: "Acabado fino para procesos de detallado.",
    description: "Lija de agua flexible para acabado y preparación de superficie.",
    categorySlug: "abrasivos",
    price: 12.9,
    unit: "pieza",
    stock: 360,
    lowStockThreshold: 50,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Lija de agua",
    imageKey: "abrasive-disc",
    daysOffset: 33,
    tiers: [
      { minQuantity: 50, price: 11.8 },
      { minQuantity: 200, price: 10.9 },
    ],
  },
  {
    name: "Disco flap zirconia grano 60",
    sku: "ABR-013",
    brand: "Acavike Select",
    shortDescription: "Acabado y desbaste controlado para metal y herrería.",
    description: "Disco flap con zirconia para preparación de superficies y remoción continua.",
    categorySlug: "abrasivos",
    price: 74.5,
    unit: "pieza",
    stock: 84,
    lowStockThreshold: 18,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Disco flap",
    imageKey: "abrasive-disc",
    daysOffset: 32,
    tiers: [
      { minQuantity: 12, price: 69.9 },
      { minQuantity: 48, price: 66.4 },
    ],
  },
  {
    name: "Rollo abrasivo óxido de aluminio 1 x 50 m",
    sku: "ABR-014",
    brand: "Acavike Select",
    shortDescription: "Consumible para lijado manual y preparación de piezas.",
    description: "Rollo abrasivo flexible para corte a la medida en mantenimiento y producción ligera.",
    categorySlug: "abrasivos",
    price: 985,
    unit: "rollo",
    stock: 22,
    lowStockThreshold: 6,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Rollo abrasivo",
    imageKey: "abrasive-disc",
    daysOffset: 31,
    tiers: [{ minQuantity: 5, price: 939 }],
  },
  {
    name: "Emplaye manual 18 pulg calibre 70",
    sku: "EMP-015",
    brand: "Acavike Supply",
    shortDescription: "Película stretch para aseguramiento de tarimas y surtido diario.",
    description: "Emplaye manual transparente para resguardo, consolidación y embarque interno.",
    categorySlug: "empaque",
    price: 219,
    unit: "rollo",
    stock: 140,
    lowStockThreshold: 20,
    leadTimeText: "Entrega inmediata",
    isFeatured: true,
    imageAlt: "Emplaye manual",
    imageKey: "stretch-film",
    daysOffset: 30,
    tiers: [
      { minQuantity: 12, price: 204.5 },
      { minQuantity: 48, price: 196.9 },
    ],
  },
  {
    name: "Cinta canela hot melt 48 x 150 m",
    sku: "EMP-016",
    brand: "Acavike Supply",
    shortDescription: "Cierre confiable para cajas y embarque recurrente.",
    description: "Cinta canela de alta adherencia para operaciones de surtido, packing y despacho.",
    categorySlug: "empaque",
    price: 58.9,
    unit: "rollo",
    stock: 260,
    lowStockThreshold: 40,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Cinta canela",
    imageKey: "stretch-film",
    daysOffset: 29,
    tiers: [
      { minQuantity: 36, price: 54.9 },
      { minQuantity: 144, price: 49.9 },
    ],
  },
  {
    name: "Cinta masking industrial 2 pulg",
    sku: "EMP-017",
    brand: "Acavike Supply",
    shortDescription: "Protección temporal para pintura, marcado y procesos ligeros.",
    description: "Cinta masking para sujeción, marcado y protección en taller y mantenimiento.",
    categorySlug: "empaque",
    price: 42.5,
    unit: "rollo",
    stock: 170,
    lowStockThreshold: 24,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Cinta masking",
    imageKey: "stretch-film",
    daysOffset: 28,
    tiers: [
      { minQuantity: 24, price: 39.5 },
      { minQuantity: 96, price: 36.8 },
    ],
  },
  {
    name: "Guante de nitrilo negro caja 100",
    sku: "SEG-018",
    brand: "Acavike Guard",
    shortDescription: "Protección desechable para mantenimiento, limpieza y empaque.",
    description: "Caja con guantes de nitrilo para manejo general en procesos industriales y logísticos.",
    categorySlug: "equipo-de-seguridad",
    price: 249,
    unit: "caja",
    stock: 58,
    lowStockThreshold: 12,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Guantes de nitrilo",
    imageKey: "glove",
    daysOffset: 27,
    tiers: [
      { minQuantity: 10, price: 233 },
      { minQuantity: 40, price: 221.5 },
    ],
  },
  {
    name: "Guante de carnaza reforzado",
    sku: "SEG-019",
    brand: "Acavike Guard",
    shortDescription: "Protección para maniobras, carga y uso rudo ligero.",
    description: "Guante de carnaza con costura reforzada para manejo de materiales y patio.",
    categorySlug: "equipo-de-seguridad",
    price: 96,
    unit: "par",
    stock: 66,
    lowStockThreshold: 14,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Guante de carnaza",
    imageKey: "glove",
    daysOffset: 26,
    tiers: [
      { minQuantity: 12, price: 89.5 },
      { minQuantity: 48, price: 84.9 },
    ],
  },
  {
    name: "Faja lumbar industrial ajustable",
    sku: "SEG-020",
    brand: "Acavike Guard",
    shortDescription: "Soporte para labores repetitivas y maniobra ligera.",
    description: "Faja lumbar con ajuste de velcro para apoyo operativo en almacenaje y surtido.",
    categorySlug: "equipo-de-seguridad",
    price: 310,
    unit: "pieza",
    stock: 25,
    lowStockThreshold: 6,
    leadTimeText: "48 horas",
    isFeatured: false,
    imageAlt: "Soporte lumbar",
    imageKey: "glove",
    daysOffset: 25,
    tiers: [{ minQuantity: 8, price: 289 }],
  },
  {
    name: "Limpiador multiusos espuma activa 20 L",
    sku: "LMP-021",
    brand: "Acavike Clean",
    shortDescription: "Solución para superficies de trabajo, áreas comunes y mobiliario.",
    description: "Limpiador espumoso concentrado para aplicación en planta, oficina y almacén.",
    categorySlug: "limpieza",
    price: 689,
    unit: "garrafa",
    stock: 18,
    lowStockThreshold: 5,
    leadTimeText: "48 horas",
    isFeatured: false,
    imageAlt: "Limpiador multiusos",
    imageKey: "degreaser",
    daysOffset: 24,
    tiers: [{ minQuantity: 4, price: 652 }],
  },
  {
    name: "Sanitizante base cuaternarios 5 L",
    sku: "LMP-022",
    brand: "Acavike Clean",
    shortDescription: "Desinfección operativa para áreas de contacto frecuente.",
    description: "Sanitizante concentrado para rutinas de limpieza industrial y corporativa.",
    categorySlug: "limpieza",
    price: 228,
    unit: "garrafa",
    stock: 46,
    lowStockThreshold: 10,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Sanitizante industrial",
    imageKey: "degreaser",
    daysOffset: 23,
    tiers: [
      { minQuantity: 6, price: 214.5 },
      { minQuantity: 24, price: 204.9 },
    ],
  },
  {
    name: "Paño industrial absorbente paquete 50",
    sku: "LMP-023",
    brand: "Acavike Clean",
    shortDescription: "Apoyo para limpieza rápida de derrames y superficies.",
    description: "Paño industrial de alta absorción para mantenimiento, taller y líneas de ensamble.",
    categorySlug: "limpieza",
    price: 179,
    unit: "paquete",
    stock: 72,
    lowStockThreshold: 12,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Paño industrial",
    imageKey: "degreaser",
    daysOffset: 22,
    tiers: [
      { minQuantity: 8, price: 169.5 },
      { minQuantity: 32, price: 159 },
    ],
  },
  {
    name: "Kit de hidratación para sala de juntas",
    sku: "COM-024",
    brand: "Acavike Pantry",
    shortDescription: "Presentación lista para reuniones y visitas operativas.",
    description: "Kit con agua, vasos y servilletas para atención interna en oficinas y salas.",
    categorySlug: "comestibles",
    price: 289,
    unit: "kit",
    stock: 22,
    lowStockThreshold: 6,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Kit de hidratación",
    imageKey: "coffee-kit",
    daysOffset: 21,
    tiers: [{ minQuantity: 6, price: 274 }],
  },
  {
    name: "Paquete té y endulzante surtido",
    sku: "COM-025",
    brand: "Acavike Pantry",
    shortDescription: "Complemento para servicio interno y salas de espera.",
    description: "Paquete surtido para estaciones de bebidas calientes con consumo administrativo.",
    categorySlug: "comestibles",
    price: 198,
    unit: "paquete",
    stock: 19,
    lowStockThreshold: 5,
    leadTimeText: "48 horas",
    isFeatured: false,
    imageAlt: "Paquete de té",
    imageKey: "coffee-kit",
    daysOffset: 20,
    tiers: [{ minQuantity: 8, price: 186.5 }],
  },
  {
    name: "Agua purificada caja 24 piezas",
    sku: "COM-026",
    brand: "Acavike Pantry",
    shortDescription: "Abasto simple para oficina, caseta y juntas operativas.",
    description: "Caja con botellas individuales para consumo interno y atención a visitantes.",
    categorySlug: "comestibles",
    price: 174,
    unit: "caja",
    stock: 34,
    lowStockThreshold: 8,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Caja de agua",
    imageKey: "coffee-kit",
    daysOffset: 19,
    tiers: [{ minQuantity: 10, price: 165 }],
  },
  {
    name: "Perfil PTR 2 x 2 cal 14",
    sku: "FAB-027",
    brand: "Acavike Metal",
    shortDescription: "Material para soportes, racks y adecuaciones industriales.",
    description: "Perfil PTR comercial para fabricación ligera y trabajos de mantenimiento estructural.",
    categorySlug: "fabricacion",
    price: 264,
    unit: "barra",
    stock: 31,
    lowStockThreshold: 8,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Perfil PTR",
    imageKey: "steel-profile",
    daysOffset: 18,
    tiers: [
      { minQuantity: 10, price: 249 },
      { minQuantity: 30, price: 238.5 },
    ],
  },
  {
    name: "Solera acero al carbón 1/4 x 2 pulg",
    sku: "FAB-028",
    brand: "Acavike Metal",
    shortDescription: "Componente para herrería ligera y armado auxiliar.",
    description: "Solera para montaje, refuerzo y fabricación menor en planta o proyecto.",
    categorySlug: "fabricacion",
    price: 149,
    unit: "barra",
    stock: 42,
    lowStockThreshold: 10,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Solera de acero",
    imageKey: "steel-profile",
    daysOffset: 17,
    tiers: [{ minQuantity: 12, price: 141 }],
  },
  {
    name: "Canal monten C estructural 6 m",
    sku: "FAB-029",
    brand: "Acavike Metal",
    shortDescription: "Perfil para soporte, techumbre ligera y adecuaciones de obra.",
    description: "Canal monten comercial para proyectos internos y estructuras auxiliares.",
    categorySlug: "fabricacion",
    price: 468,
    unit: "barra",
    stock: 18,
    lowStockThreshold: 4,
    leadTimeText: "4 a 6 días hábiles",
    isFeatured: false,
    imageAlt: "Canal monten",
    imageKey: "steel-profile",
    daysOffset: 16,
    tiers: [{ minQuantity: 8, price: 445 }],
  },
  {
    name: "Silla visitante apilable",
    sku: "OFF-030",
    brand: "Acavike Office",
    shortDescription: "Asiento práctico para recepción y juntas cortas.",
    description: "Silla de visita con estructura metálica para áreas administrativas y espera.",
    categorySlug: "oficina",
    price: 899,
    unit: "pieza",
    stock: 20,
    lowStockThreshold: 6,
    leadTimeText: "3 a 5 días hábiles",
    isFeatured: false,
    imageAlt: "Silla visitante",
    imageKey: "office-chair",
    daysOffset: 15,
    tiers: [{ minQuantity: 12, price: 839 }],
  },
  {
    name: "Kit ergonómico de escritorio",
    sku: "OFF-031",
    brand: "Acavike Office",
    shortDescription: "Accesorios básicos para estación administrativa ordenada.",
    description: "Kit con soporte, descansamuñecas y organizadores para mejorar la operación diaria.",
    categorySlug: "oficina",
    price: 640,
    unit: "kit",
    stock: 15,
    lowStockThreshold: 4,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Kit ergonómico",
    imageKey: "office-chair",
    daysOffset: 14,
    tiers: [{ minQuantity: 6, price: 599 }],
  },
  {
    name: "Base para monitor metálica",
    sku: "OFF-032",
    brand: "Acavike Office",
    shortDescription: "Soporte simple para escritorio y estaciones de captura.",
    description: "Base metálica para elevar monitor y liberar espacio operativo en oficina.",
    categorySlug: "oficina",
    price: 389,
    unit: "pieza",
    stock: 24,
    lowStockThreshold: 6,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Base para monitor",
    imageKey: "office-chair",
    daysOffset: 13,
    tiers: [{ minQuantity: 8, price: 364 }],
  },
  {
    name: "Escalera multifuncional aluminio 13 peldaños",
    sku: "CON-033",
    brand: "Acavike Build",
    shortDescription: "Apoyo para mantenimiento, almacén y adecuaciones internas.",
    description: "Escalera articulada para trabajos ligeros con transporte sencillo y armado rápido.",
    categorySlug: "construccion",
    price: 3290,
    unit: "pieza",
    stock: 8,
    lowStockThreshold: 2,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Escalera multifuncional",
    imageKey: "ladder",
    daysOffset: 12,
    tiers: [{ minQuantity: 3, price: 3149 }],
  },
  {
    name: "Cono vial reflejante 70 cm",
    sku: "CON-034",
    brand: "Acavike Build",
    shortDescription: "Control visual temporal para obra, patio y maniobras.",
    description: "Cono de señalización para seguridad operativa en interiores y exteriores.",
    categorySlug: "construccion",
    price: 248,
    unit: "pieza",
    stock: 54,
    lowStockThreshold: 10,
    leadTimeText: "24 horas",
    isFeatured: false,
    imageAlt: "Cono vial",
    imageKey: "warning-tape",
    daysOffset: 11,
    tiers: [{ minQuantity: 12, price: 229 }],
  },
  {
    name: "Kit delimitación de obra ligera",
    sku: "CON-035",
    brand: "Acavike Build",
    shortDescription: "Combo para cierres temporales y seguridad en trabajos internos.",
    description: "Kit con cinta preventiva y apoyos básicos para delimitar zonas de mantenimiento.",
    categorySlug: "construccion",
    price: 745,
    unit: "kit",
    stock: 16,
    lowStockThreshold: 4,
    leadTimeText: "48 horas",
    isFeatured: false,
    imageAlt: "Kit de delimitación",
    imageKey: "warning-tape",
    daysOffset: 10,
    tiers: [{ minQuantity: 4, price: 699 }],
  },
  {
    name: "Rotomartillo SDS Plus 800 W",
    sku: "HER-036",
    brand: "Acavike Tools",
    shortDescription: "Equipo para mantenimiento civil y anclajes ligeros.",
    description: "Rotomartillo de uso intensivo para perforación en concreto y adecuaciones operativas.",
    categorySlug: "herramienta",
    price: 2840,
    unit: "pieza",
    stock: 7,
    lowStockThreshold: 2,
    leadTimeText: "72 horas",
    isFeatured: false,
    imageAlt: "Rotomartillo",
    imageKey: "drill",
    daysOffset: 9,
    tiers: [{ minQuantity: 3, price: 2690 }],
  },
  {
    name: "Esmeril angular 4.5 pulg",
    sku: "HER-037",
    brand: "Acavike Tools",
    shortDescription: "Herramienta compacta para corte, desbaste y ajuste en campo.",
    description: "Esmeril angular de operación continua para mantenimiento mecánico y fabricación ligera.",
    categorySlug: "herramienta",
    price: 1675,
    unit: "pieza",
    stock: 11,
    lowStockThreshold: 3,
    leadTimeText: "48 horas",
    isFeatured: false,
    imageAlt: "Esmeril angular",
    imageKey: "drill",
    daysOffset: 8,
    tiers: [{ minQuantity: 4, price: 1589 }],
  },
  {
    name: "Atornillador de impacto 20 V",
    sku: "HER-038",
    brand: "Acavike Tools",
    shortDescription: "Equipo para montaje rápido y trabajos de instalación.",
    description: "Atornillador compacto para cuadrillas de mantenimiento, montaje y operación diaria.",
    categorySlug: "herramienta",
    price: 2190,
    unit: "pieza",
    stock: 10,
    lowStockThreshold: 3,
    leadTimeText: "48 horas",
    isFeatured: false,
    imageAlt: "Atornillador de impacto",
    imageKey: "drill",
    daysOffset: 7,
    tiers: [{ minQuantity: 4, price: 2085 }],
  },
  {
    name: "Tornillo autotaladrante punta broca",
    sku: "TOR-039",
    brand: "Acavike Fix",
    shortDescription: "Fijación rápida para lámina, canal y armado ligero.",
    description: "Tornillo autotaladrante para instalación metálica y adecuaciones de mantenimiento.",
    categorySlug: "tornilleria",
    price: 2.95,
    unit: "pieza",
    stock: 1400,
    lowStockThreshold: 200,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Tornillo autotaladrante",
    imageKey: "screw",
    daysOffset: 6,
    tiers: [
      { minQuantity: 250, price: 2.62 },
      { minQuantity: 1000, price: 2.39 },
    ],
  },
  {
    name: "Tuerca de seguridad nylon 5/16",
    sku: "TOR-040",
    brand: "Acavike Fix",
    shortDescription: "Fijación con resistencia a vibración para ensambles operativos.",
    description: "Tuerca con inserto nylon para mantenimiento preventivo y montaje mecánico.",
    categorySlug: "tornilleria",
    price: 1.8,
    unit: "pieza",
    stock: 1800,
    lowStockThreshold: 260,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Tuerca de seguridad",
    imageKey: "screw",
    daysOffset: 5,
    tiers: [
      { minQuantity: 250, price: 1.58 },
      { minQuantity: 1000, price: 1.42 },
    ],
  },
  {
    name: "Rondana plana galvanizada 1/4",
    sku: "TOR-041",
    brand: "Acavike Fix",
    shortDescription: "Complemento para ensamble mecánico y montaje general.",
    description: "Rondana galvanizada de uso industrial para fijación en operación y mantenimiento.",
    categorySlug: "tornilleria",
    price: 0.95,
    unit: "pieza",
    stock: 2400,
    lowStockThreshold: 300,
    leadTimeText: "Entrega inmediata",
    isFeatured: false,
    imageAlt: "Rondana galvanizada",
    imageKey: "screw",
    daysOffset: 4,
    tiers: [
      { minQuantity: 500, price: 0.82 },
      { minQuantity: 2000, price: 0.75 },
    ],
  },
  {
    name: "Renta de rotomartillo SDS por día",
    sku: "REN-042",
    brand: "Acavike Rental",
    shortDescription: "Apoyo para trabajos puntuales de perforación y anclaje.",
    description: "Renta diaria con disponibilidad programada para cuadrillas y adecuaciones operativas.",
    categorySlug: "renta",
    price: 780,
    unit: "día",
    stock: 3,
    lowStockThreshold: 1,
    leadTimeText: "Bajo programación",
    isFeatured: false,
    imageAlt: "Renta de rotomartillo",
    imageKey: "drill",
    daysOffset: 3,
    tiers: [{ minQuantity: 3, price: 725 }],
  },
  {
    name: "Renta de kit de señalización vial",
    sku: "REN-043",
    brand: "Acavike Rental",
    shortDescription: "Cobertura temporal para maniobras, acceso y zonas restringidas.",
    description: "Kit de renta con elementos de señalización para obra, mantenimiento y control interno.",
    categorySlug: "renta",
    price: 540,
    unit: "día",
    stock: 5,
    lowStockThreshold: 1,
    leadTimeText: "Bajo programación",
    isFeatured: false,
    imageAlt: "Renta de señalización vial",
    imageKey: "warning-tape",
    daysOffset: 2,
    tiers: [{ minQuantity: 5, price: 495 }],
  },
  {
    name: "Renta de polipasto manual 1 t",
    sku: "REN-044",
    brand: "Acavike Rental",
    shortDescription: "Equipo auxiliar para movimientos puntuales en taller o montaje.",
    description: "Renta diaria de polipasto manual para maniobras controladas en mantenimiento y proyecto.",
    categorySlug: "renta",
    price: 920,
    unit: "día",
    stock: 2,
    lowStockThreshold: 1,
    leadTimeText: "Bajo programación",
    isFeatured: false,
    imageAlt: "Renta de polipasto manual",
    imageKey: "steel-profile",
    daysOffset: 1,
    tiers: [{ minQuantity: 3, price: 865 }],
  },
];
